# Generated by Django 3.2 on 2022-05-28 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0002_auto_20220526_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-last_modified_date'], 'verbose_name_plural': 'Accouncements'},
        ),
        migrations.AlterModelOptions(
            name='attendances',
            options={'verbose_name_plural': 'Attendances'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='testimony',
        ),
    ]
